---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

Data science is essentially, \"the collection, organization, analysis, and visualization of large amounts of data\" (mastersindatascience.org). In this class, we gained hands-on experience with almost all of these concepts. In terms of \"collection\", while we did not learn or practice the ways to properly collect data without incurring biases, we were able to handle many different file types such as .txt, .xlsx, and .csv and were able to create our own \"datasets\" from the information we gathered. For example, in Challenge 4 we collected housing prices for a range of years for different locations and created a dataset to use for analysis. The organization and analysis aspect of data science consists of all the data wrangling and computation we did with dplyr. This is where I feel the bulk of our class was focused on and I feel that my skills in this area were the most developed. We learned how to filter out null values, change data types of variables, and pivot our dataset to perform
certain calculations. For example, in Lab 4 we extensively used dplyr to filter data based on specific values or based on data in another dataset. We also were able to change the orientation of our data by using pivot functions to easily calculate summary statistics. Working with dplyr reminded me of a previous class when I was working with SQL. Without these tools, manually altering the dataset would be an impossible task. We also explored working with many different data types such as strings and dates through the lubridate and stringr packages. In practice activity 5, we were able to use stringr take advantage of regular expressions and we were able to create time series visualizations with lubridate. Visualization, such as plots and tables, was another large concept in this class. I was able to develop my plot-making skills through ggplot starting in week 2 which allowed me to apply my creativity in a simple and intuitive way. These skills grew as we progressed through the quarter when working with different data types such as dates. In week #5, through Will Chase\'s presentation on best visualization practices, I was able to create plots that were easily interpretable. In Challenge 9, I also learned how to use the kable and kableExtra packages to create professional and easy-to-interpret tables for the reader that were far better than the default output. that Overall, I feel that my skills in each aspect of being a data scientist have grown tremendously. I feel confident that I could be provided with a dataset and could proficiently modify it to obtain meaningful statistics as well as information-rich visualizations.
